In [1]:
import sys
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

import collections
import argparse
from Bio import SeqIO
from itertools import product

In [4]:
# load the train and test datasets accordingly
train_X = pd.read_csv('/Users/eesoonhang/Desktop/capstone_data/train_in.csv', skiprows=0)
train_y = pd.read_csv('/Users/eesoonhang/Desktop/capstone_data/train_out.csv', skiprows=0)
test_X = pd.read_csv('/Users/eesoonhang/Desktop/capstone_data/test_in.csv', skiprows=0)
test_y = pd.read_csv('/Users/eesoonhang/Desktop/capstone_data/test_out.csv', skiprows=0)

# check the shape of all datasets
print('train_X = ' + str(train_X.shape) + '\n' + 'train_y = ' + str(train_y.shape) + '\n' + 'test_X = ' + str(test_X.shape) + '\n' + 'test_y = ' + str(test_y.shape) + '\n')

train_X = (304661, 1001)
train_y = (304661, 12)
test_X = (1200, 1001)
test_y = (1200, 12)

In [6]:
# randomly pick 10 samples from train_X to set up testing environment
sample_X = train_X.sample(n=10, replace=False)
sample_X.head(10)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V992,V993,V994,V995,V996,V997,V998,V999,V1000,V1001
223314,G,G,G,G,T,T,C,T,G,T,...,N,N,N,N,N,N,N,N,N,N
272010,T,C,G,G,G,G,G,T,C,G,...,N,N,N,N,N,N,N,N,N,N
172271,C,T,G,A,G,A,A,C,T,C,...,A,T,G,T,G,T,G,T,G,T
92831,T,A,A,T,C,T,C,A,T,T,...,C,C,T,G,T,C,T,A,T,A
131801,A,A,T,T,T,T,G,T,A,G,...,T,A,A,G,C,T,C,T,A,G
106250,A,A,A,A,A,A,T,T,A,T,...,T,G,T,C,T,A,T,C,A,C
144686,C,A,C,T,A,A,G,T,A,T,...,A,G,G,C,C,A,T,A,G,A
115734,A,C,A,T,G,G,A,G,A,C,...,A,G,A,T,T,A,T,A,C,C
184578,A,T,G,A,A,T,C,G,G,C,...,C,T,G,G,T,C,T,C,G,A
60931,G,G,A,C,C,A,C,C,T,A,...,T,C,T,T,C,T,T,C,C,C

# Performance feature extraction with NAC, DAC & TAC

# Note: Code below assume the input data is always an RNA sequence

In [9]:
nucleotide = ['C', 'G', 'A', 'T']
result = product(nucleotide, repeat=2)

In [ ]:
def extractFeature_via_nacSeq(k, inputData):
    
    # for RNA sequence only
    global nucleotide = ['C', 'G', 'A', 'T']
    
    # perform cartesian-product based on k-value
    p_combinations =

In [ ]:
def headerNAC(k):
    global listTotal, caracteres
    listTotal = []
    file = open(foutput, 'a')
    file.write('%s,' % ('nameseq'))
    permsList = [''.join(str(i) for i in x) for x in product(caracteres, repeat=k)]
    # print (permsList)
    for perm in permsList:
        # print (perm)
        listTotal.append(perm)
        file.write('%s,' % (str(perm)))
    file.write('label')
    file.write('\n')
    return

In [ ]:
# k defines the number of consecutive nucleotide acid
# k=1 : NAC
# k=2 : DAC
# k=3 : TAC
def nacSeq(k):
    global probabilities
    headerNAC(k)
    for seq_record in SeqIO.parse(finput, 'fasta'):
        seq = seq_record.seq
        seq = seq.upper()	
        name_seq = seq_record.name
        probabilities = []
        kmer = {}
        totalWindows = (len(seq) - k) + 1 # (L - k + 1)
        permsList = [''.join(str(i) for i in x) for x in product(caracteres, repeat=k)]
        for key in permsList:
            kmer[key] = 0
        kmer = collections.OrderedDict(sorted(kmer.items()))
        for subseq in chunks_two(seq, k):
            if subseq in kmer:
                # print(subseq)
                kmer[subseq] = kmer[subseq] + 1
            else:
                kmer[subseq] = 1
        for key, value in kmer.items():
            # print (key)
            # print (value)
            probabilities.append([str(key), value/totalWindows])
        file_record(name_seq)
    return